[package]
name = "finql"
version = "0.6.2"
authors = ["Mark Beinker <mwb@quantlink.de>"]
edition = "2018"
description = "A quantitative finance toolbox"
license = "MIT OR Apache-2.0"
repository = "https://github.com/xemwebe/finql"
readme = "README.md"
keywords = ["finance", "calendar", "bond", "period", "pricing"]
categories = ["date-and-time","mathematics"]

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
text_io = "0.1"
computus = "1.0"
serde = { version = "1.0.*", features = ["derive"] }
serde_json = "1.0"
argmin = "0.2"
rusqlite = "0.22"
postgres = { version = "0.17", features = ["with-chrono-0_4"] }
tokio-postgres = "0.5"
yahoo-finance = "0.2"
gurufocus_api = { version = "0.3.2", path = "../gurufocus_api" }
rand = "0.7"
eodhistoricaldata_api =  {version = "0.1", path = "../eodhistoricaldata_api"}
